### ISSUE TITLE
Hapi 13 peerDependencies Support?

### ISSUE THREAD

**Issue by bflad** [ethanmick/hapi-router-coffee#2]
Hey Ethan,

We were hoping to upgrade from Hapi 11 to 13 and receive the following error running `npm install`:

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/bflad/.nvm/versions/node/v4.4.1/bin/node" "/Users/bflad/.nvm/versions/node/v4.4.1/bin/npm" "install"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package hapi@13.4.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer hapi-router-coffee@1.3.0 wants hapi@~11.x.x
```

The peerDependencies are currently too strict to support both 11 and 13:

```
"peerDependencies": {
  "hapi": "~11.x.x"
},
```

Are you planning on cutting a release with 13 support? Please let me know if you need any help testing or upgrading. Thanks!

**Comment by ethanmick** [comment]
Hey, thanks for stopping by! I'll cut a new release today for Hapi 12, 13 and you can lock in the new version.

**Comment by ethanmick** [comment]
Okay, I've updated the package to be much less picky about the version of Hapi, accepting `*`. This should fix the issue for you, most recent version is now `1.5.0`.

Let me know if that's not the case!

**Comment by bflad** [comment]
Worked like a charm, thanks!!
