### ISSUE TITLE
route, not routes

### ISSUE THREAD

**Issue by githistory** [ethanmick/hapi-router-coffee#3]
https://github.com/ethanmick/hapi-router-coffee/blob/e5cc2fa9e9f61167f1e49dd644408fbda83f276b/lib/index.coffee#L21

The s should be removed.

Great plugin! Thanks!

**Comment by ethanmick** [comment]
Will #4 fix this issue? Thanks for the bug report!

**Comment by ethanmick** [comment]
Resolved with #4, now on `master`.
